name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  before_after:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/after.png
    - assets/before.png
    - assets/after.jpg
    - assets/before.jpg
